# Generated by Django 3.2.9 on 2021-11-25 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(verbose_name='created')),
                ('changed', models.DateTimeField(verbose_name='changed')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('reg_no', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('iban', models.CharField(max_length=255)),
                ('vat_no', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(verbose_name='created')),
                ('changed', models.DateTimeField(verbose_name='changed')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('reg_no', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(verbose_name='created')),
                ('changed', models.DateTimeField(verbose_name='changed')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('due_date', models.DateTimeField(verbose_name='due date')),
                ('reference', models.CharField(max_length=255)),
                ('description', models.JSONField(max_length=1000)),
                ('invoice_vat', models.FloatField(max_length=20)),
                ('invoice_total', models.FloatField(max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.customer')),
            ],
        ),
    ]
